version: '3'
services:
  web:
    links:
      - mysql
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8080:8080"
  mysql:
    build: ./docker/db
    restart: always
    env_file:
      - .env
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
